### ISSUE TITLE
ClassNotFoundException: net.sqlcipher.database.SQliteDatabase

### ISSUE THREAD

**Issue by jakev** [jakev/SqlCipherHook#1]
```
10-24 11:16:45.843  4915  4915 E Xposed  : de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: net.sqlcipher.database.SQLiteDatabase
10-24 11:16:45.843  4915  4915 E Xposed  : 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:62)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:251)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at com.jakev.sqlcipherhook.Main.handleLoadPackage(Main.java:46)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:193)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:720)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at android.os.Looper.loop(Looper.java:148)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at android.app.ActivityThread.main(ActivityThread.java:5417)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at java.lang.reflect.Method.invoke(Native Method)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
10-24 11:16:45.843  4915  4915 E Xposed  : Caused by: java.lang.ClassNotFoundException: net.sqlcipher.database.SQLiteDatabase
10-24 11:16:45.843  4915  4915 E Xposed  : 	at java.lang.Class.classForName(Native Method)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at java.lang.Class.forName(Class.java:324)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:60)
10-24 11:16:45.843  4915  4915 E Xposed  : 	... 17 more
10-24 11:16:45.843  4915  4915 E Xposed  : Caused by: java.lang.ClassNotFoundException: Didn't find class "net.sqlcipher.database.SQLiteDatabase" on path: DexPathList[[zip file "/data/app/com.google.android.instantapps.supervisor-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.instantapps.supervisor-1/lib/arm, /data/app/com.google.android.instantapps.supervisor-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
10-24 11:16:45.843  4915  4915 E Xposed  : 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
10-24 11:16:45.843  4915  4915 E Xposed  : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
10-24 11:16:45.843  4915  4915 E Xposed  : 	... 21 more
10-24 11:16:45.843  4915  4915 E Xposed  : 	Suppressed: java.lang.ClassNotFoundException: net.sqlcipher.database.SQLiteDatabase
10-24 11:16:45.843  4915  4915 E Xposed  : 		at java.lang.Class.classForName(Native Method)
10-24 11:16:45.843  4915  4915 E Xposed  : 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
10-24 11:16:45.843  4915  4915 E Xposed  : 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
10-24 11:16:45.843  4915  4915 E Xposed  : 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
10-24 11:16:45.843  4915  4915 E Xposed  : 		... 22 more
10-24 11:16:45.843  4915  4915 E Xposed  : 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by jakev** [comment]
Closed via: https://github.com/jakev/SqlCipherHook/commit/8025c47ec0b902cc5957be0f768f3b9926cc4cfc
