### ISSUE TITLE
java.lang.NoSuchMethodError: net.sqlcipher.database.SQLiteDatabase#openDatabase(java.lang.String,java.lang.String,net.sqlcipher.database.SQLiteDatabase.CursorFactory,int,net.sqlcipher.database.SQLiteDatabaseHook)#exact

### ISSUE THREAD

**Issue by jakev** [jakev/SqlCipherHook#2]
```
10-24 11:30:22.221  8891  8891 E Xposed  : java.lang.NoSuchMethodError: net.sqlcipher.database.SQLiteDatabase#openDatabase(java.lang.String,java.lang.String,net.sqlcipher.database.SQLiteDatabase.CursorFactory,int,net.sqlcipher.database.SQLiteDatabaseHook)#exact
10-24 11:30:22.221  8891  8891 E Xposed  : 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:339)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:176)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:251)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at com.jakev.sqlcipherhook.Main.hookSqlCipher(Main.java:67)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at com.jakev.sqlcipherhook.Main.access$100(Main.java:31)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at com.jakev.sqlcipherhook.Main$1.afterHookedMethod(Main.java:50)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:754)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at android.app.Application.attach(<Xposed>)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at android.app.Instrumentation.newApplication(Instrumentation.java:997)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at android.app.Instrumentation.newApplication(Instrumentation.java:981)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4680)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at android.os.Looper.loop(Looper.java:148)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at android.app.ActivityThread.main(ActivityThread.java:5417)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at java.lang.reflect.Method.invoke(Native Method)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-24 11:30:22.221  8891  8891 E Xposed  : 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
```

**Comment by jakev** [comment]
This appears to be an issue with Xposed and Interfaces method arguments? Either way, fixed with: https://github.com/jakev/SqlCipherHook/commit/a00257a41ed16ee95f0dbba26cc12c6920aafff3
